/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controlador.AdminTerminalController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modelo.AdminTerminal;
import modelo.Caseta;
import singleton.Singleton;

/**
 *
 * @author usuario
 */
public class VentanaAdminTerminal extends javax.swing.JFrame implements ActionListener {

   private JButton [][] botones;
   private AdminTerminalController controller;
   private AdminTerminal admin;
   
   
    public VentanaAdminTerminal(AdminTerminal admin) {
        initComponents();
        setLocationRelativeTo(this);
        controller = new AdminTerminalController();
        this.admin = admin;
        
        dibujarBotones();      
        pintarBotones();
    }
    
    private void dibujarBotones() {
    int ancho = 60;
    int alto = 40;
    int x = 30;
    int y = 30;
    
    this.botones = new JButton[4][];

    for (int i = 0; i < botones.length; i++) {
        
        botones[i] = new JButton[i >= 1?2:5];
        for (int j = 0; j < botones[i].length; j++) {
            botones[i][j] = new JButton();
            if(i == 1 && j == 1){             
                x+=210;
            }else if(i == 3 && j == 0){
                x+=210;
            }
            
            botones[i][j].setBounds(x,y,ancho,alto);

            botones[i][j].addActionListener(this);
            panelBotones.add(botones[i][j]);
            x+=70;
        }
        x = 30;
        y += 40;
    }
    }
    
   public void pintarBotones() {
    for (int i = 0; i < botones.length; i++) {
        for (int j = 0; j < botones[i].length; j++) {
            Caseta caseta = controller.getCaseta(i, j);
            botones[i][j].setBackground(caseta.getEstado().equals(Caseta.OCUPADO) ? Color.RED : Color.WHITE);
        }
    }
}
    
    public void actualizarVentana(){
        pintarBotones();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder("Casetas"));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addGap(0, 178, Short.MAX_VALUE)
                .addComponent(btnAtras))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

      VentanaLogin ventanaLogin = new VentanaLogin();
      ventanaLogin.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables

   @Override
public void actionPerformed(ActionEvent e) {
    for (int i = 0; i < botones.length; i++) {
        for (int j = 0; j < botones[i].length; j++) {
            if (e.getSource().equals(botones[i][j])) {
                Caseta caseta = controller.getCaseta(i,j);
                VentanaRegistroFlota vga = new VentanaRegistroFlota(caseta,admin);
                vga.setVisible(true);
                this.dispose();
            }
        }
    }
}

}
